### ISSUE TITLE
COMException (0x80020009):  Invalid chat name

### ISSUE THREAD

**Issue by eigenein** [eigenein/skype-historian#48]
Originally reported by: **Pavel Perestoronin (Bitbucket: [eigenein](http://bitbucket.org/eigenein), GitHub: [eigenein](http://github.com/eigenein))**

---

Приложение не может получить список месаг у конкретного чата, несмотря на то, что получен объект класса `IChat`.

---
- Bitbucket: https://bitbucket.org/eigenein/skype-historian/issue/48

**Comment by eigenein** [comment]
_Original comment by_ **Pavel Perestoronin (Bitbucket: [eigenein](http://bitbucket.org/eigenein), GitHub: [eigenein](http://github.com/eigenein))**:

---

Ещё один пользователь прислал часть лога:

```
2012-09-25 21:39:53.0039 Info: Started processing echo123, sander.verhagen chat.
2012-09-25 21:39:53.0039 Debug: Creating a file: C:\Users\sverhagen\Desktop\trillian\historian\Skype sep-25-2012-20-45-31\feb 2009\echo123, sander.verhagen.xml
2012-09-25 21:39:53.0289 Info: Messages processing is finished.
2012-09-25 21:39:53.0299 Info: Date filter skipped count: 0
2012-09-25 21:39:53.0299 Info: Started processing a chat.
2012-09-25 21:39:53.0299 Warn: The exception was raised at invocation target.
System.Runtime.InteropServices.COMException (0x80020009):  Invalid chat name
   at Skype4COMWrapper.IChat.get_Messages()
   at SkypeHistorian.Controls.Pages.ExportingPage.<>c__DisplayClass20.<GetMessageCollection>b__1e()
   at SkypeHistorian.Helpers.SafeInvoker.Invoke[TResult](Func`1 target, TResult& result)
2012-09-25 21:39:53.0299 Info: StatusCode: CannotGetMessageCollection
2012-09-25 21:39:53.0299 Info: Closing streams ...
2012-09-25 21:40:03.5469 Info: 156211 messages of 286755 are exported.
2012-09-25 21:40:03.5469 Info: 4503 chats of 8336 are exported.
2012-09-25 21:40:03.5469 Info: Page Finishing is requested.
2012-09-25 21:40:03.5469 Info: Selecting page Finishing
2012-09-25 21:40:03.5469 Info: Finishing is initializing
```

**Comment by eigenein** [comment]
_Original comment by_ **Pavel Perestoronin (Bitbucket: [eigenein](http://bitbucket.org/eigenein), GitHub: [eigenein](http://github.com/eigenein))**:

---

http://sourceforge.net/news/?group_id=171321

```
* Some chats report "invalid chat name" (since this only happens for chats in a period of time, suspect that certain version of Skype messed up the data storage format of the chats)COMException when trying to access its field
```

**Comment by eigenein** [comment]
_Original comment by_ **Pavel Perestoronin (Bitbucket: [eigenein](http://bitbucket.org/eigenein), GitHub: [eigenein](http://github.com/eigenein))**:

---

https://jira.skype.com/browse/SCL-875

```
Marco Cimmino added a comment - 01/Aug/12 8:41 AM
Ok this has been fixed in the next release. Thanks for reporting it. 
```

# Потенциальное решение проблемы - обновление Skype4COM.

# Попробовать задампить chat name.

**Comment by eigenein** [comment]
_Original comment by_ **Pavel Perestoronin (Bitbucket: [eigenein](http://bitbucket.org/eigenein), GitHub: [eigenein](http://github.com/eigenein))**:

---

Нужно также попытаться поднять вот этот ишшус: https://jira.skype.com/browse/SPA-707

**Comment by eigenein** [comment]
_Original comment by_ **Pavel Perestoronin (Bitbucket: [eigenein](http://bitbucket.org/eigenein), GitHub: [eigenein](http://github.com/eigenein))**:

---

Sander написал, что бага воспроизводится и на Skype4COM 1.0.36.0, и 1.0.38.0, на Skype 5.10.0.116.

James - на Skype 5.9.0.123.

**Comment by eigenein** [comment]
_Original comment by_ **Pavel Perestoronin (Bitbucket: [eigenein](http://bitbucket.org/eigenein), GitHub: [eigenein](http://github.com/eigenein))**:

---

Нужно пытаться дебажиться на стороне пользователей с помощью http://developer.skype.com/accessories/tracer. Это сможет показать, на моей ли стороне находится бага.

**Comment by eigenein** [comment]
_Original comment by_ **Pavel Perestoronin (Bitbucket: [eigenein](http://bitbucket.org/eigenein), GitHub: [eigenein](http://github.com/eigenein))**:

---

Workaround в коммите 65279ea2281d01474c14530d8e1f0c1958d29935.
